name: firestore_wrapper_web
environment:
    sdk: '>=2.0.0 <3.0.0'
dependencies:
    firebase: ^5.0.3
    firestore_wrapper:
        git:
            url: https://github.com/paulorobertocruz/firestore_wrapper.git
            path: packages/firestore_wrapper
